from daycare import Daycare
from baby import Baby
import numpy as np

#Randomly generate an (x, y) coordinate, normally distributed around the origin
def generate_location(rng, std=1.0):
    x = rng.normal(loc=0.0, scale=std)
    y = rng.normal(loc=0.0, scale=std)
    
    x = min(std*3, max(-std*3, x))
    y = min(std*3, max(-std*3, y))

    return [x, y]

#Generate capacities for the daycares. Poisson distribution is used so that most 
#capacities are around the mean but occasionally they are higher. Also
#does not generate negative values, and is discrete so we get integer values.
def generate_capacity(rng, mean_capacity):
    return int(rng.poisson(mean_capacity))


#Generates daycares and puts them in a list. Uses generate_location() and generate_capacity()
def generate_daycares(
    n_daycares,
    rng,
    location_std=1.0,
    mean_capacity=2.5
):
    daycares = []

    for i in range(n_daycares):
        location = generate_location(
            rng,
            std=location_std
        )

        capacity = generate_capacity(
            rng,
            mean_capacity=mean_capacity        
            )

        daycare = Daycare(
            id=i,
            location=location,
            capacity=capacity
        )

        daycares.append(daycare)

    return daycares

#Generates babies and puts them in a list. Uses generate_location(). Preferences are 
#generated by putting the daycares in a random order in the preferences list.
def generate_babies(
    n_babies,
    daycares,
    rng,
    location_std=1.0
):
    babies = []

    daycare_ids = [daycare.id for daycare in daycares]

    for i in range(n_babies):
        location = generate_location(
            rng,
            std=location_std
        )

        preferences = list(
            rng.permutation(daycare_ids)
        )

        baby = Baby(
            id=i,
            location=location,
            preferences=preferences
        )

        babies.append(baby)

    return babies

#Reset the capacity of the daycares to allow for another algorithm
def reset_daycares(daycares):
    for daycare in daycares:
        daycare.reset()

#Count blocking pairs (stability, Gale-Shapley). A pair (baby, daycare) is
#blocking if the baby prefers this daycare over her own assignment, and the
#daycare has a free seat or prefers this baby over its least liked baby.
def count_blocking_pairs(babies, daycares, assignments):
    n_matched = {dc.id: 0 for dc in daycares}
    min_v = {dc.id: np.inf for dc in daycares}
    for baby, j in zip(babies, assignments):
        if j is not None:
            n_matched[j] += 1
            min_v[j] = min(min_v[j], daycares[j].utilities[baby.id])

    count = 0
    for baby, j_own in zip(babies, assignments):
        u_own = baby.utilities[j_own] if j_own is not None else -np.inf
        for dc in daycares:
            if dc.id == j_own or baby.utilities[dc.id] <= u_own:
                continue
            has_room = n_matched[dc.id] < dc.capacity
            prefers_baby = dc.utilities[baby.id] > min_v[dc.id]
            if has_room or prefers_baby:
                count += 1
    return count

#Run a specific algorithm and output assignment results
def run_algorithm(algorithm, babies, daycares, print_results=True):

    assignments = []

    total_baby_utility = 0.0
    total_daycare_utility = 0.0
    unmatched_babies = 0

    for baby in babies:

        daycare_id = algorithm.match_baby(baby)

        assignments.append(daycare_id)

        if daycare_id is None:
            unmatched_babies += 1
            continue

        daycare = daycares[daycare_id]

        total_baby_utility += baby.utilities[daycare_id]
        total_daycare_utility += daycare.utilities[baby.id]

  

    if len(babies) > 0:
        average_baby_utility = total_baby_utility / len(babies)
        average_daycare_utility = total_daycare_utility / (len(babies))
    else:
        average_baby_utility = 0
        average_daycare_utility = 0

    blocking_pairs = count_blocking_pairs(babies, daycares, assignments)

    results = {
        "total_baby_utility": total_baby_utility,
        "total_daycare_utility": total_daycare_utility,
        "unmatched_babies": unmatched_babies,
        "blocking_pairs": blocking_pairs,
        "average_baby_utility": average_baby_utility,
        "average_daycare_utility": average_daycare_utility,
        "Algorithm score": average_daycare_utility + average_baby_utility
    }

    if print_results:
        print("================================")
        print(f"Total unmatched babies: {unmatched_babies}" )
        print(f"Average baby utility: {average_baby_utility}" )
        print(f"Average daycare utility: {average_daycare_utility}" )
        print(f"Algorithm score {average_baby_utility + average_daycare_utility}")
        print(f"Blocking pairs: {blocking_pairs}")


    return results, assignments